Refactor docker image building scripts.
AlexsLemonade/refinebio pull request #3158
Opened 2022-12-02 01:54 UTC by arkid15r

## Issue Number

#3129 

## Purpose/Implementation Notes
Update scripts for better docker cache leveraging, improve readability:
  - Add remote builder support option.
  - Add existing image based cache.
  - Set `amd64` as a default architecture.
  - Add optional `arm64` build support for `update_my_docker_images.sh`.
  - Consolidate api/common/workers images build logic.

## Methods
NA

## Types of changes

What types of changes does your code introduce?

NA

## Functional tests
NA

## Checklist

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots
NA

2023-03-29 18:54 UTC, davidsmejia commented on scripts/update_my_docker_images.sh
> +There is also optional arguments:
```suggestion
There are also optional arguments:
```

2023-03-29 19:02 UTC, davidsmejia requested changes
Default to amd64 and then have an optional flag to target arm

2023-03-29 19:02 UTC, davidsmejia commented on scripts/update_my_docker_images.sh
> +-b sets a remote Docker builder for amd64 image builds.
We should simplify this, default to `adm64` and have optarg `-x` to target `arm64`. Though I also think we probably shouldn't enable this until all images can be built on `arm64`. Would like to hear your thoughts on this.

2023-03-29 19:04 UTC, davidsmejia commented on scripts/update_my_docker_images.sh
> +-b sets a remote Docker builder for amd64 image builds.
Actually I am unsure what this option does functionally.

2023-05-10 18:07 UTC, arkid15r commented
Suppressed by https://github.com/AlexsLemonade/refinebio/pull/3285

2023-05-10 18:07 UTC, closed without merging