Fix downloaders tests
AlexsLemonade/refinebio pull request #3231
Opened 2023-03-06 22:06 UTC by arkid15r

## Purpose/Implementation Notes

Fix tests for `downloader_no_op_tests`:
  - Update requirements.
  - Fix aspera downloader.
  - Migrate to new sra data source.
  - Update docker image.

## Types of changes

- Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

2023-03-29 19:42 UTC, davidsmejia requested changes
LGTM just one documentation request.

2023-03-29 19:42 UTC, davidsmejia commented on workers/keys/asperaweb_id_dsa.openssh
I think that we should have a `README.md` in this folder that explains the origins of this key and it's purpose for future devs.

2023-04-03 18:55 UTC, arkid15r commented on workers/keys/asperaweb_id_dsa.openssh
Done.

2023-04-06 18:32 UTC, davidsmejia commented on workers/keys/README.md
> +See https://www.ibm.com/docs/en/aspera-on-cloud?topic=ak-fasp-security-aspera-connect-transfer-client-authorized-keys-aspshell
```suggestion
See [IBM's documentation](https://www.ibm.com/docs/en/aspera-on-cloud?topic=ak-fasp-security-aspera-connect-transfer-client-authorized-keys-aspshell)
```

2023-04-06 18:32 UTC, davidsmejia approved these changes
LGTM 🐼

2023-04-06 21:08 UTC, arkid15r commented on workers/keys/README.md
> +See https://www.ibm.com/docs/en/aspera-on-cloud?topic=ak-fasp-security-aspera-connect-transfer-client-authorized-keys-aspshell
👍

2023-04-06 21:09 UTC, merged