Fix common, foreman tests
AlexsLemonade/refinebio pull request #3254
Opened 2023-04-11 20:44 UTC by arkid15r

## Purpose/Implementation Notes

Migrate common/migrations image to `dr_base`.
Move foreman tests to tests directory.
Add separate settings file (tests/settings.py).
Refactor import according to the new structure.

## Methods

NA

## Types of changes

What types of changes does your code introduce?
- Bugfix (non-breaking change which fixes an issue)

## Functional tests

NA

## Checklist
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots

NA

2023-04-13 19:07 UTC, davidsmejia requested changes
LGTM just some minor suggestions for improvement

2023-04-13 19:07 UTC, davidsmejia commented on foreman/tests/foreman/management/commands/test_update_experiment_metadata.py
> +        experiment = Experiment.objects.get_or_create(accession_code=experiment.accession_code)[0]
```suggestion
        experiment, _ = Experiment.objects.get_or_create(accession_code=experiment.accession_code)
```

2023-04-13 22:49 UTC, arkid15r commented on foreman/data_refinery_foreman/foreman/management/commands/update_experiment_metadata.py
> -                        request_url = EXPERIMENTS_URL + experiment.accession_code
I'm going to clean that up after the ArrayExpress migration is done.

2023-04-13 22:49 UTC, arkid15r commented on foreman/data_refinery_foreman/surveyor/array_express.py
> +        return parsed_data
Done.

2023-04-13 22:49 UTC, arkid15r commented on foreman/tests/foreman/management/commands/test_update_experiment_metadata.py
> +        experiment = Experiment.objects.get_or_create(accession_code=experiment.accession_code)[0]
Done

2023-04-14 15:17 UTC, davidsmejia approved these changes
LGTM!

2023-04-14 15:18 UTC, merged